# Generated by Django 6.0.4 on 2026-04-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0002_alter_student_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
    ]
