# Generated by Django 6.0.4 on 2026-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6),
        ),
    ]
