# Generated by Django 6.0.4 on 2026-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0005_student_created_at_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='documents',
            field=models.FileField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=4, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
